name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        type: choice
        description: select terraform action
        options:
        - apply
        - destroy
        required: true
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main

permissions:
      id-token: write # for aws oidc connection
      contents: read   # for actions/checkout
      pull-requests: write # for GitHub bot to comment PR
      
jobs:

  terraform:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: Debug IAM files
        run: |
          echo "Current commit:"
          git rev-parse HEAD

          echo "Searching for github_actions role..."
          grep -R 'resource "aws_iam_role" "github_actions"' modules/iam || true

          echo "least-privilege-policy.tf"
          cat modules/iam/least-privilege-policy.tf

          echo "outputs.tf"
          cat modules/iam/outputs.tf

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          
         terraform_version: 1.7.5

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -recursive

      - name: Terraform Init
        id: init
      
        run: 
          terraform init -upgrade
        
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color 

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -out=tfplan -no-color

      - name: Terraform Apply
        id: apply 
        if: ${{ github.event.inputs.terraform_action == 'apply' }}
        run: terraform apply -auto-approve
      
      - name: Terraform destroy
        id: destroy 
        if: ${{ github.event.inputs.terraform_action == 'destroy' }}
        run: terraform destroy -auto-approve
        #if: github.ref == 'refs/heads/main' && github.event_name == 'push'